name: 'Run one-off task on ECS'
description: 'Run a task on ECS and waits for ECS task to finish.'
branding:
  icon: 'activity'
  color: 'white'
inputs:
  cluster:
    description: "The name of the ECS service's cluster.  Will default to the 'default' cluster"
    required: false
  service:
    description: 'The name of the service'
    required: true
  override-container:
    description: 'The container whose command should be overridden'
    required: false
  override-container-command:
    description: 'The command to to be run on the overrided container'
    required: false

outputs:
  task-arn:
    description: 'The ARN for the tash that finished running'
  status:
    description: 'The status of the task, success for sucesssful tasks.'
  task-definition:
    description: 'Task definition uid'

runs:
  using: 'node24'
  main: 'dist/index.js'
